type Establishment {
    name        : String!
    type        : Int!
    owner       : User!
    image       : String
    verified    : Boolean
    code        : Int

    workers     : [User!]!
    products    : [Product!]!

    client      : [String]!
}

input EstInput {
    name        : String!
    type        : Int
}

input EstItem {
    estCode: Int!
    idProduct: String!
    amount: Int
    price: Float
}

type Mutation {
    CreateEstablishment( est: EstInput! ): Response
    addProduct( item: EstItem! ): Response
}

type Query {
    getStablishments                : [Establishment!]!
    getStablishment( code: Int! )   : Establishment
}