
    type Contact {
        address     : String
        phone       : String
        country     : String
        city        : String
    }
    
    type Account {
        creation_date   : String
        last_update     : String
        token           : String
        recovery_token  : String 
    }

    type Profile {
        name        : String!
        lastName    : String!
        image       : String
    }

    type User {
        id          : ID!
        email       : String!
        pass        : String!
        profile     : Profile!
        contact     : Contact
        account     : Account
    }

    input ProfileInput {
        name        : String!
        lastName    : String!
    }


    input UserInput {
        email       : String!
        pass        : String!
        profile     : ProfileInput!
    }

    type Query {
        
        PasswordRecovery( email: String! ): Response
    }

    type Mutation {
        Login(email: String!, pass: String!): User
        CreateUser( user: UserInput! ): Response
        UpdateUser: User
    }